[build]
  publish = "."           # publicamos la ra√≠z del proyecto
  command = ""            # no necesitamos comando de build si es solo HTML/CSS/JS

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
